# Pandas 기초연습문제

In [ ]:
import pandas as pd

In [2]:
score={'학번':[201524213,201621223,201621233, 201611111, 201722222],
       '이름':['오지환','박용택','정성훈', '다니엘', '지민'],
       '학과':['경영정보','경영정보','경영정보','컴퓨터공학','컴퓨터공학'],
       'Quiz':[15,20,10,17,18],
       '중간고사':[20,20,15,18,16]}

df= pd.DataFrame(score)
df

# score 딕셔너리를 생성 후 dataframe으로 만든 후 df에 넣어줍니다.

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
2  201621233  정성훈   경영정보    10    15
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16

In [3]:
df['학번'] # "학번" column 출력

0    201524213
1    201621223
2    201621233
3    201611111
4    201722222
Name: 학번, dtype: int64

In [4]:
df[['이름', '중간고사']] # "이름", "중간고사" columns 동시에 출력

이름  중간고사
0  오지환    20
1  박용택    20
2  정성훈    15
3  다니엘    18
4   지민    16

In [5]:
df = df.reindex([2, 0, 4, 1, 3]) # reindex를 이용해여 rows의 순서 변경 가능
df

학번   이름     학과  Quiz  중간고사
2  201621233  정성훈   경영정보    10    15
0  201524213  오지환   경영정보    15    20
4  201722222   지민  컴퓨터공학    18    16
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

In [9]:
print(df.iloc[3]) # 3 + 1  번째 row 출력 
print(df.loc[1])  # index number가 1인 row 출력


학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object
학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object


In [10]:
print(df.iloc[:, [1, 4]]) # 1 + 1,3번째 columns 모두 출력
print(df.loc[:, ['이름', '중간고사']]) # column attribute 명이 "이름", "중간고사"인 열 모두 출력

    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18
    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18


In [11]:
df['중간고사'].mean()

17.8

In [12]:
df['중간고사'].idxmin() # 중간고사 점수가 가장 낮은 학생의 index 출력

2

In [13]:
df.loc[df['Quiz'].idxmax(), '학번'] # 퀴즈 점수가 가장 높은 학생의 학번을 구하시오
#df.loc[df['Quiz'].idxmax()]['학번'] 

201621223

In [14]:
df.describe() # descfribe를 통해 dataframe의 기본적인 통계적인 정보 알 수 있습니다.

학번       Quiz       중간고사
count  5.000000e+00   5.000000   5.000000
mean   2.016200e+08  16.000000  17.800000
std    7.018995e+04   3.807887   2.280351
min    2.015242e+08  10.000000  15.000000
25%    2.016111e+08  15.000000  16.000000
50%    2.016212e+08  17.000000  18.000000
75%    2.016212e+08  18.000000  20.000000
max    2.017222e+08  20.000000  20.000000

In [15]:
df.sort_values('중간고사', ascending=False) # 중간고사 점수를 내림차순으로 정렬

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16
2  201621233  정성훈   경영정보    10    15

In [16]:
quiz_mean = df['Quiz'].mean()
df[df['Quiz'] > quiz_mean]['이름'] # df에서 "이름" 출력 - 평균보다 퀴즈 점수가 높은

4     지민
1    박용택
3    다니엘
Name: 이름, dtype: object

In [17]:
quiz_mean = df['Quiz'].mean()
mid_mean = df['중간고사'].mean()
df[(df['Quiz'] > quiz_mean) & (df['중간고사'] > mid_mean)] # 퀴즈와 중간고사 점수 모두 평균 이상인 학생들의 record 출력

학번   이름     학과  Quiz  중간고사
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

In [18]:
df['학과'].value_counts()

경영정보     3
컴퓨터공학    2
Name: 학과, dtype: int64

In [22]:
df.groupby('학과')['중간고사'].mean() # 학과 별 중간고사의 평균 - 매우 유용해 보입니다,

학과
경영정보     18.333333
컴퓨터공학    17.000000
Name: 중간고사, dtype: float64

In [26]:
df.groupby('이름')['중간고사'].mean() # 학생 별 개개인의 중간고사 평균 

이름
다니엘    18
박용택    20
오지환    20
정성훈    15
지민     16
Name: 중간고사, dtype: int64

In [27]:
df.groupby('이름')['중간고사',"Quiz"].mean() # 학생 별 개개인의 중간고사 퀴즈 평균 

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


중간고사  Quiz
이름             
다니엘    18    17
박용택    20    20
오지환    20    15
정성훈    15    10
지민     16    18

In [30]:
df.groupby('중간고사')["Quiz"].mean()

중간고사
15    10.0
16    18.0
18    17.0
20    17.5
Name: Quiz, dtype: float64

In [20]:
df.mean() # columns 별 평균

학번      201620000.4
Quiz           16.0
중간고사           17.8
dtype: float64

In [21]:
list(df.groupby('학과')) # "학과"별로 그룹화하여 리스트 형식으로 출력

[('경영정보',
            학번   이름    학과  Quiz  중간고사
  2  201621233  정성훈  경영정보    10    15
  0  201524213  오지환  경영정보    15    20
  1  201621223  박용택  경영정보    20    20),
 ('컴퓨터공학',
            학번   이름     학과  Quiz  중간고사
  4  201722222   지민  컴퓨터공학    18    16
  3  201611111  다니엘  컴퓨터공학    17    18)]

# Numpy 기초연습문제


In [31]:
import numpy as np

In [32]:
a = np.zeros((3, 4)) # np.zeros를 이용해여 3행 4열의 배열 생성 이를 a라고 명명.
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
for i in range(a.shape[0]): # "3"행
    for j in range(a.shape[1]): # "4"열
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [39]:
num = 1
for i in range(a.shape[0]): # "3"행
    for j in range(a.shape[1]): # "4"열
        a[i, j] =  num # 행렬 a에 num을 하나씩 집어넣는다.
        num += 1 # num 1씩 증가 
a # 행렬 a 출력

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [55]:
a[1, 2] # 1 +1행 2 +1열 출력

7.0

In [56]:
a.shape # 행렬 a는 3행 4열이므로 

(3, 4)

In [57]:
a[[1], :] # 2행의 열 전부 출력

array([[5., 6., 7., 8.]])

In [58]:
a[:,[0, 2]] # 1,2 열의 행 전체 출력

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

In [59]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [60]:
a[a <= 6] # 행렬의 값이 6이하인 값 배열의 형태로 출력

array([1., 2., 3., 4., 5., 6.])

In [61]:
b = np.random.random((3, 4)) # 랜덤 행렬 생성
b

array([[0.71809808, 0.27195053, 0.9418563 , 0.35448375],
       [0.52999062, 0.3516002 , 0.92232657, 0.43219471],
       [0.30521816, 0.87437917, 0.90381321, 0.17792565]])

In [62]:
c = a * b
c

array([[0.71809808, 0.54390106, 2.82556889, 1.41793499],
       [2.64995312, 2.10960122, 6.45628599, 3.45755767],
       [2.74696341, 8.74379174, 9.94194532, 2.13510784]])

In [63]:
d = b.T b의 # 3x4 행렬을 4x3행렬로 바꿔서 출력
d

array([[0.71809808, 0.52999062, 0.30521816],
       [0.27195053, 0.3516002 , 0.87437917],
       [0.9418563 , 0.92232657, 0.90381321],
       [0.35448375, 0.43219471, 0.17792565]])

In [64]:
d.shape

(4, 3)

In [65]:
print(a.shape, d.shape)

(3, 4) (4, 3)


In [66]:
e = a.dot(d) # dot()을 이용하여 a와 d의 행렬곱을 계산하여 e에 저장
e

array([[ 5.50550302,  5.72894957,  5.47711875],
       [14.65105764, 14.67339799, 14.52246353],
       [23.79661226, 23.61784641, 23.56780831]])

In [68]:
np.sum(e, axis=0) # e에 대하여 각 행의 합을 계산

array([43.95317292, 44.02019397, 43.5673906 ])

In [ ]:
np.sum(e, axis=1) # e에 대하여 각 열의 합을 계산

# - 끝